//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.morphml.metadata.schema.Annotation;
import org.morphml.metadata.schema.Properties;
import org.morphml.metadata.schema.Units;


/**
 * Root element containing the ions used in the mechanism, the unit system of the 
 *             file (as attribute), and information on channels and/or ion concentration dynamics. Normally only the ion element and 
 *             one of channel_type, synapse_type or ion_concentration should be present.
 * 
 * <p>Java class for ChannelML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChannelML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://morphml.org/metadata/schema}metadata"/>
 *         &lt;element name="ion" type="{http://morphml.org/channelml/schema}Deprecated_Ion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="channel_type" type="{http://morphml.org/channelml/schema}ChannelType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="synapse_type" type="{http://morphml.org/channelml/schema}SynapseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ion_concentration" type="{http://morphml.org/channelml/schema}IonConcentration" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="units" use="required" type="{http://morphml.org/metadata/schema}Units" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChannelML", propOrder = {
    "notes",
    "properties",
    "annotation",
    "groups",
    "ions",
    "channelTypes",
    "synapseTypes",
    "ionConcentrations"
})
public class ChannelmlType {

    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected String notes;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Properties properties;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Annotation annotation;
    @XmlElement(name = "group", namespace = "http://morphml.org/metadata/schema")
    protected List<String> groups;
    @XmlElement(name = "ion")
    protected List<DeprecatedIon> ions;
    @XmlElement(name = "channel_type")
    protected List<ChannelType> channelTypes;
    @XmlElement(name = "synapse_type")
    protected List<SynapseType> synapseTypes;
    @XmlElement(name = "ion_concentration")
    protected List<IonConcentration> ionConcentrations;
    @XmlAttribute(required = true)
    protected Units units;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation }
     *     
     */
    public Annotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation }
     *     
     */
    public void setAnnotation(Annotation value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGroups() {
        if (groups == null) {
            groups = new ArrayList<String>();
        }
        return this.groups;
    }

    /**
     * Gets the value of the ions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeprecatedIon }
     * 
     * 
     */
    public List<DeprecatedIon> getIons() {
        if (ions == null) {
            ions = new ArrayList<DeprecatedIon>();
        }
        return this.ions;
    }

    /**
     * Gets the value of the channelTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the channelTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChannelTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChannelType }
     * 
     * 
     */
    public List<ChannelType> getChannelTypes() {
        if (channelTypes == null) {
            channelTypes = new ArrayList<ChannelType>();
        }
        return this.channelTypes;
    }

    /**
     * Gets the value of the synapseTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synapseTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynapseTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SynapseType }
     * 
     * 
     */
    public List<SynapseType> getSynapseTypes() {
        if (synapseTypes == null) {
            synapseTypes = new ArrayList<SynapseType>();
        }
        return this.synapseTypes;
    }

    /**
     * Gets the value of the ionConcentrations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ionConcentrations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIonConcentrations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IonConcentration }
     * 
     * 
     */
    public List<IonConcentration> getIonConcentrations() {
        if (ionConcentrations == null) {
            ionConcentrations = new ArrayList<IonConcentration>();
        }
        return this.ionConcentrations;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Units }
     *     
     */
    public Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Units }
     *     
     */
    public void setUnits(Units value) {
        this.units = value;
    }

}
