//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of a voltage gate. Normally this will be specified as rate equations for 
 *             alpha and beta, or for tau and inf. Deprecated! Will be removed in v2.0
 * 
 * <p>Java class for Deprecated_VoltageGate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Deprecated_VoltageGate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="initialisation" type="{http://morphml.org/channelml/schema}Initialisation" minOccurs="0"/>
 *         &lt;group ref="{http://morphml.org/channelml/schema}Deprecated_AlphaBetaForm" minOccurs="0"/>
 *         &lt;group ref="{http://morphml.org/channelml/schema}Deprecated_ExtraRateExpressions" minOccurs="0"/>
 *         &lt;element name="tau" type="{http://morphml.org/channelml/schema}Deprecated_RateConstantEqnChoice" minOccurs="0"/>
 *         &lt;element name="inf" type="{http://morphml.org/channelml/schema}Deprecated_RateConstantEqnChoice" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Deprecated_VoltageGate", propOrder = {
    "initialisation",
    "alpha",
    "beta",
    "gamma",
    "zeta",
    "tau",
    "inf"
})
public class DeprecatedVoltageGate {

    protected Initialisation initialisation;
    protected DeprecatedRateConstantEqnChoice alpha;
    protected DeprecatedRateConstantEqnChoice beta;
    protected DeprecatedRateConstantEqnChoice gamma;
    protected DeprecatedRateConstantEqnChoice zeta;
    protected DeprecatedRateConstantEqnChoice tau;
    protected DeprecatedRateConstantEqnChoice inf;

    /**
     * Gets the value of the initialisation property.
     * 
     * @return
     *     possible object is
     *     {@link Initialisation }
     *     
     */
    public Initialisation getInitialisation() {
        return initialisation;
    }

    /**
     * Sets the value of the initialisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initialisation }
     *     
     */
    public void setInitialisation(Initialisation value) {
        this.initialisation = value;
    }

    /**
     * Gets the value of the alpha property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setAlpha(DeprecatedRateConstantEqnChoice value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setBeta(DeprecatedRateConstantEqnChoice value) {
        this.beta = value;
    }

    /**
     * Gets the value of the gamma property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getGamma() {
        return gamma;
    }

    /**
     * Sets the value of the gamma property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setGamma(DeprecatedRateConstantEqnChoice value) {
        this.gamma = value;
    }

    /**
     * Gets the value of the zeta property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getZeta() {
        return zeta;
    }

    /**
     * Sets the value of the zeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setZeta(DeprecatedRateConstantEqnChoice value) {
        this.zeta = value;
    }

    /**
     * Gets the value of the tau property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getTau() {
        return tau;
    }

    /**
     * Sets the value of the tau property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setTau(DeprecatedRateConstantEqnChoice value) {
        this.tau = value;
    }

    /**
     * Gets the value of the inf property.
     * 
     * @return
     *     possible object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public DeprecatedRateConstantEqnChoice getInf() {
        return inf;
    }

    /**
     * Sets the value of the inf property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeprecatedRateConstantEqnChoice }
     *     
     */
    public void setInf(DeprecatedRateConstantEqnChoice value) {
        this.inf = value;
    }

}
