//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Deprecated_CoreEquationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Deprecated_CoreEquationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="exponential"/>
 *     &lt;enumeration value="sigmoid"/>
 *     &lt;enumeration value="linoid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Deprecated_CoreEquationType")
@XmlEnum
public enum DeprecatedCoreEquationType {


    /**
     * Of the form: A * exp(k * (v-d))
     * 
     */
    @XmlEnumValue("exponential")
    EXPONENTIAL("exponential"),

    /**
     * Of the form: A / (1 + exp(k * (v-d)))
     * 
     */
    @XmlEnumValue("sigmoid")
    SIGMOID("sigmoid"),

    /**
     * Of the form: A * (k * (v-d)) / (1 - exp(-(k * (v-d))))
     * 
     */
    @XmlEnumValue("linoid")
    LINOID("linoid");
    private final String value;

    DeprecatedCoreEquationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DeprecatedCoreEquationType fromValue(String v) {
        for (DeprecatedCoreEquationType c: DeprecatedCoreEquationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
