//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A synaptic type with facilitating and depressing amplitude. 
 * 
 * Extends MultiDecaySynapse
 * 
 * <p>Java class for FacDepSynapse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FacDepSynapse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://morphml.org/channelml/schema}MultiDecaySynapse">
 *       &lt;sequence>
 *         &lt;element name="plasticity" type="{http://morphml.org/channelml/schema}FacDep"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacDepSynapse", propOrder = {
    "plasticity"
})
public class FacDepSynapse
    extends MultiDecaySynapse
{

    @XmlElement(required = true)
    protected FacDep plasticity;

    /**
     * Gets the value of the plasticity property.
     * 
     * @return
     *     possible object is
     *     {@link FacDep }
     *     
     */
    public FacDep getPlasticity() {
        return plasticity;
    }

    /**
     * Sets the value of the plasticity property.
     * 
     * @param value
     *     allowed object is
     *     {@link FacDep }
     *     
     */
    public void setPlasticity(FacDep value) {
        this.plasticity = value;
    }

}
