//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Preferred element for defining a gate since v1.7.3. Definition of a single voltage/concentration dependent gate, 
 *             with explicit definition of open and closed states and information on the transition rates between them.
 * 
 * <p>Java class for GatingComplex complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GatingComplex">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="closed_state" type="{http://morphml.org/channelml/schema}ClosedState" maxOccurs="unbounded"/>
 *         &lt;element name="open_state" type="{http://morphml.org/channelml/schema}OpenState" maxOccurs="unbounded"/>
 *         &lt;element name="initialisation" type="{http://morphml.org/channelml/schema}Initialisation" minOccurs="0"/>
 *         &lt;element name="transition" type="{http://morphml.org/channelml/schema}Transition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="time_course" type="{http://morphml.org/channelml/schema}TimeCourse" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="steady_state" type="{http://morphml.org/channelml/schema}SteadyState" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="instances" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GatingComplex", propOrder = {
    "closedStates",
    "openStates",
    "initialisation",
    "transitions",
    "timeCourses",
    "steadyStates"
})
public class GatingComplex {

    @XmlElement(name = "closed_state", required = true)
    protected List<ClosedState> closedStates;
    @XmlElement(name = "open_state", required = true)
    protected List<OpenState> openStates;
    protected Initialisation initialisation;
    @XmlElement(name = "transition")
    protected List<Transition> transitions;
    @XmlElement(name = "time_course")
    protected List<TimeCourse> timeCourses;
    @XmlElement(name = "steady_state")
    protected List<SteadyState> steadyStates;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger instances;

    /**
     * Gets the value of the closedStates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the closedStates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClosedStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClosedState }
     * 
     * 
     */
    public List<ClosedState> getClosedStates() {
        if (closedStates == null) {
            closedStates = new ArrayList<ClosedState>();
        }
        return this.closedStates;
    }

    /**
     * Gets the value of the openStates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the openStates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOpenStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OpenState }
     * 
     * 
     */
    public List<OpenState> getOpenStates() {
        if (openStates == null) {
            openStates = new ArrayList<OpenState>();
        }
        return this.openStates;
    }

    /**
     * Gets the value of the initialisation property.
     * 
     * @return
     *     possible object is
     *     {@link Initialisation }
     *     
     */
    public Initialisation getInitialisation() {
        return initialisation;
    }

    /**
     * Sets the value of the initialisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Initialisation }
     *     
     */
    public void setInitialisation(Initialisation value) {
        this.initialisation = value;
    }

    /**
     * Gets the value of the transitions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transition }
     * 
     * 
     */
    public List<Transition> getTransitions() {
        if (transitions == null) {
            transitions = new ArrayList<Transition>();
        }
        return this.transitions;
    }

    /**
     * Gets the value of the timeCourses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the timeCourses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTimeCourses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TimeCourse }
     * 
     * 
     */
    public List<TimeCourse> getTimeCourses() {
        if (timeCourses == null) {
            timeCourses = new ArrayList<TimeCourse>();
        }
        return this.timeCourses;
    }

    /**
     * Gets the value of the steadyStates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the steadyStates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSteadyStates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SteadyState }
     * 
     * 
     */
    public List<SteadyState> getSteadyStates() {
        if (steadyStates == null) {
            steadyStates = new ArrayList<SteadyState>();
        }
        return this.steadyStates;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the instances property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInstances() {
        return instances;
    }

    /**
     * Sets the value of the instances property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInstances(BigInteger value) {
        this.instances = value;
    }

}
