//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.morphml.metadata.schema.Annotation;
import org.morphml.metadata.schema.Authors;
import org.morphml.metadata.schema.ModelDBReference;
import org.morphml.metadata.schema.NeuroMorphoRef;
import org.morphml.metadata.schema.NeuronDBReference;
import org.morphml.metadata.schema.Properties;
import org.morphml.metadata.schema.Publication;
import org.morphml.metadata.schema.Status;


/**
 * Specification of how an ion concentration alters with time, e.g. calcium dynamics. This may influence other
 *                    channels (e.g. Ca dependent K channels), and other mechanisms may have a contribution to the concentration of the ion specified here.
 * 
 * <p>Java class for IonConcentration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IonConcentration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://morphml.org/metadata/schema}Status" minOccurs="0"/>
 *         &lt;group ref="{http://morphml.org/metadata/schema}metadata"/>
 *         &lt;group ref="{http://morphml.org/metadata/schema}referencedata"/>
 *         &lt;element name="ion_species" type="{http://morphml.org/channelml/schema}IonSpecies"/>
 *         &lt;choice>
 *           &lt;element name="decaying_pool_model" type="{http://morphml.org/channelml/schema}DecayingPoolModel"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IonConcentration", propOrder = {
    "status",
    "notes",
    "properties",
    "annotation",
    "groups",
    "authorList",
    "publications",
    "neuronDBreves",
    "modelDBreves",
    "neuroMorphoReves",
    "ionSpecies",
    "decayingPoolModel"
})
public class IonConcentration {

    protected Status status;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected String notes;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Properties properties;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Annotation annotation;
    @XmlElement(name = "group", namespace = "http://morphml.org/metadata/schema")
    protected List<String> groups;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Authors authorList;
    @XmlElement(name = "publication", namespace = "http://morphml.org/metadata/schema")
    protected List<Publication> publications;
    @XmlElement(name = "neuronDBref", namespace = "http://morphml.org/metadata/schema")
    protected List<NeuronDBReference> neuronDBreves;
    @XmlElement(name = "modelDBref", namespace = "http://morphml.org/metadata/schema")
    protected List<ModelDBReference> modelDBreves;
    @XmlElement(name = "neuroMorphoRef", namespace = "http://morphml.org/metadata/schema")
    protected List<NeuroMorphoRef> neuroMorphoReves;
    @XmlElement(name = "ion_species", required = true)
    protected IonSpecies ionSpecies;
    @XmlElement(name = "decaying_pool_model")
    protected DecayingPoolModel decayingPoolModel;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation }
     *     
     */
    public Annotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation }
     *     
     */
    public void setAnnotation(Annotation value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGroups() {
        if (groups == null) {
            groups = new ArrayList<String>();
        }
        return this.groups;
    }

    /**
     * Gets the value of the authorList property.
     * 
     * @return
     *     possible object is
     *     {@link Authors }
     *     
     */
    public Authors getAuthorList() {
        return authorList;
    }

    /**
     * Sets the value of the authorList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Authors }
     *     
     */
    public void setAuthorList(Authors value) {
        this.authorList = value;
    }

    /**
     * Gets the value of the publications property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publications property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublications().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Publication }
     * 
     * 
     */
    public List<Publication> getPublications() {
        if (publications == null) {
            publications = new ArrayList<Publication>();
        }
        return this.publications;
    }

    /**
     * Gets the value of the neuronDBreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neuronDBreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeuronDBreves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeuronDBReference }
     * 
     * 
     */
    public List<NeuronDBReference> getNeuronDBreves() {
        if (neuronDBreves == null) {
            neuronDBreves = new ArrayList<NeuronDBReference>();
        }
        return this.neuronDBreves;
    }

    /**
     * Gets the value of the modelDBreves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelDBreves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelDBreves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelDBReference }
     * 
     * 
     */
    public List<ModelDBReference> getModelDBreves() {
        if (modelDBreves == null) {
            modelDBreves = new ArrayList<ModelDBReference>();
        }
        return this.modelDBreves;
    }

    /**
     * Gets the value of the neuroMorphoReves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neuroMorphoReves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeuroMorphoReves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeuroMorphoRef }
     * 
     * 
     */
    public List<NeuroMorphoRef> getNeuroMorphoReves() {
        if (neuroMorphoReves == null) {
            neuroMorphoReves = new ArrayList<NeuroMorphoRef>();
        }
        return this.neuroMorphoReves;
    }

    /**
     * Gets the value of the ionSpecies property.
     * 
     * @return
     *     possible object is
     *     {@link IonSpecies }
     *     
     */
    public IonSpecies getIonSpecies() {
        return ionSpecies;
    }

    /**
     * Sets the value of the ionSpecies property.
     * 
     * @param value
     *     allowed object is
     *     {@link IonSpecies }
     *     
     */
    public void setIonSpecies(IonSpecies value) {
        this.ionSpecies = value;
    }

    /**
     * Gets the value of the decayingPoolModel property.
     * 
     * @return
     *     possible object is
     *     {@link DecayingPoolModel }
     *     
     */
    public DecayingPoolModel getDecayingPoolModel() {
        return decayingPoolModel;
    }

    /**
     * Sets the value of the decayingPoolModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecayingPoolModel }
     *     
     */
    public void setDecayingPoolModel(DecayingPoolModel value) {
        this.decayingPoolModel = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
