//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * A more complex synaptic mechanism featuring up to 4 exponential components (1 rise and 3 decay).
 *             Currently there is only an implementation of this in a NEURON mod file. Attributed added can be gmax_2, tau_decay_2, gmax_3 and tau_decay_3.
 *             The overall conductance is effectively a linear sum of 3 independent conductances, all with the same rise time and different decays.
 *             Note that the gmaxes are specific for each conductance and scaling is calculated for each individually, so the maximum total conductance (gmax + gmax_2 + gmax_3) 
 *             will only be reached when tau_decay = tau_decay_2 = tau_decay_3, otherwise peaks will not overlap.  
 * 
 * Extends DoubleExponentialSynapse
 * 
 * <p>Java class for MultiDecaySynapse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultiDecaySynapse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://morphml.org/channelml/schema}DoubleExponentialSynapse">
 *       &lt;attGroup ref="{http://morphml.org/channelml/schema}ThirdDecay"/>
 *       &lt;attGroup ref="{http://morphml.org/channelml/schema}SecondDecay"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultiDecaySynapse")
@XmlSeeAlso({
    StdpSynapse.class,
    FacDepSynapse.class
})
public class MultiDecaySynapse
    extends DoubleExponentialSynapse
{

    @XmlAttribute(name = "max_conductance_3")
    protected Double maxConductance3;
    @XmlAttribute(name = "decay_time_3")
    protected Double decayTime3;
    @XmlAttribute(name = "max_conductance_2")
    protected Double maxConductance2;
    @XmlAttribute(name = "decay_time_2")
    protected Double decayTime2;

    /**
     * Gets the value of the maxConductance3 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxConductance3() {
        return maxConductance3;
    }

    /**
     * Sets the value of the maxConductance3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxConductance3(Double value) {
        this.maxConductance3 = value;
    }

    /**
     * Gets the value of the decayTime3 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDecayTime3() {
        return decayTime3;
    }

    /**
     * Sets the value of the decayTime3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDecayTime3(Double value) {
        this.decayTime3 = value;
    }

    /**
     * Gets the value of the maxConductance2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxConductance2() {
        return maxConductance2;
    }

    /**
     * Sets the value of the maxConductance2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxConductance2(Double value) {
        this.maxConductance2 = value;
    }

    /**
     * Gets the value of the decayTime2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDecayTime2() {
        return decayTime2;
    }

    /**
     * Sets the value of the decayTime2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDecayTime2(Double value) {
        this.decayTime2 = value;
    }

}
