//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information on the volume of the ion pool
 * 
 * <p>Java class for PoolVolumeInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoolVolumeInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="shell_thickness" type="{http://morphml.org/biophysics/schema}LengthValue" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="shell_thickness" type="{http://morphml.org/biophysics/schema}LengthValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoolVolumeInfo", propOrder = {
    "shellThicknessDeprecated"
})
public class PoolVolumeInfo {

    @XmlElement(name = "shell_thickness")
    protected Double shellThicknessDeprecated;
    @XmlAttribute(name = "shell_thickness")
    protected Double shellThickness;

    /**
     * Gets the value of the shellThicknessDeprecated property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getShellThicknessDeprecated() {
        return shellThicknessDeprecated;
    }

    /**
     * Sets the value of the shellThicknessDeprecated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setShellThicknessDeprecated(Double value) {
        this.shellThicknessDeprecated = value;
    }

    /**
     * Gets the value of the shellThickness property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getShellThickness() {
        return shellThickness;
    }

    /**
     * Sets the value of the shellThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setShellThickness(Double value) {
        this.shellThickness = value;
    }

}
