//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Q10 scaling affects the tau in the rate equations. It allows rate equations determined at one temperature to be used at a different temperature.
 *             If tauExp is the experimentally measured tau, the rate at temperature T is given by tau(T) = tauExp / q10_factor ^ ((T - experimental_temp)/10). NOTE: if fixed_q10 is specified
 *             the expression will be tau(T) = tauExp / fixed_q10, and the experimental_temp can be used to check that a simulation is running
 *             at the desired temperature. 
 * 
 * <p>Java class for Q10Settings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Q10Settings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="gate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fixed_q10" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="q10_factor" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="experimental_temp" use="required" type="{http://morphml.org/biophysics/schema}TemperatureValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Q10Settings")
public class Q10Settings {

    @XmlAttribute
    protected String gate;
    @XmlAttribute(name = "fixed_q10")
    protected Double fixedQ10;
    @XmlAttribute(name = "q10_factor")
    protected Double q10Factor;
    @XmlAttribute(name = "experimental_temp", required = true)
    protected double experimentalTemp;

    /**
     * Gets the value of the gate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGate() {
        return gate;
    }

    /**
     * Sets the value of the gate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGate(String value) {
        this.gate = value;
    }

    /**
     * Gets the value of the fixedQ10 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getFixedQ10() {
        return fixedQ10;
    }

    /**
     * Sets the value of the fixedQ10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setFixedQ10(Double value) {
        this.fixedQ10 = value;
    }

    /**
     * Gets the value of the q10Factor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getQ10Factor() {
        return q10Factor;
    }

    /**
     * Sets the value of the q10Factor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setQ10Factor(Double value) {
        this.q10Factor = value;
    }

    /**
     * Gets the value of the experimentalTemp property.
     * 
     */
    public double getExperimentalTemp() {
        return experimentalTemp;
    }

    /**
     * Sets the value of the experimentalTemp property.
     * 
     */
    public void setExperimentalTemp(double value) {
        this.experimentalTemp = value;
    }

}
