//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * A synaptic mechanism implementing basic Spike Timing Dependent Plasticity based on Song and Abbott, 2001. See mapping to NEURON mod file for implementation details.
 * 
 * <p>Java class for StdpDep complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StdpDep">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tau_ltp" use="required" type="{http://morphml.org/biophysics/schema}TimeConstantValue" />
 *       &lt;attribute name="del_weight_ltp" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="tau_ltd" use="required" type="{http://morphml.org/biophysics/schema}TimeConstantValue" />
 *       &lt;attribute name="del_weight_ltd" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="max_syn_weight" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="post_spike_thresh" use="required" type="{http://morphml.org/biophysics/schema}VoltageValue" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StdpDep")
public class StdpDep {

    @XmlAttribute(name = "tau_ltp", required = true)
    protected double tauLtp;
    @XmlAttribute(name = "del_weight_ltp", required = true)
    protected double delWeightLtp;
    @XmlAttribute(name = "tau_ltd", required = true)
    protected double tauLtd;
    @XmlAttribute(name = "del_weight_ltd", required = true)
    protected double delWeightLtd;
    @XmlAttribute(name = "max_syn_weight", required = true)
    protected double maxSynWeight;
    @XmlAttribute(name = "post_spike_thresh", required = true)
    protected double postSpikeThresh;

    /**
     * Gets the value of the tauLtp property.
     * 
     */
    public double getTauLtp() {
        return tauLtp;
    }

    /**
     * Sets the value of the tauLtp property.
     * 
     */
    public void setTauLtp(double value) {
        this.tauLtp = value;
    }

    /**
     * Gets the value of the delWeightLtp property.
     * 
     */
    public double getDelWeightLtp() {
        return delWeightLtp;
    }

    /**
     * Sets the value of the delWeightLtp property.
     * 
     */
    public void setDelWeightLtp(double value) {
        this.delWeightLtp = value;
    }

    /**
     * Gets the value of the tauLtd property.
     * 
     */
    public double getTauLtd() {
        return tauLtd;
    }

    /**
     * Sets the value of the tauLtd property.
     * 
     */
    public void setTauLtd(double value) {
        this.tauLtd = value;
    }

    /**
     * Gets the value of the delWeightLtd property.
     * 
     */
    public double getDelWeightLtd() {
        return delWeightLtd;
    }

    /**
     * Sets the value of the delWeightLtd property.
     * 
     */
    public void setDelWeightLtd(double value) {
        this.delWeightLtd = value;
    }

    /**
     * Gets the value of the maxSynWeight property.
     * 
     */
    public double getMaxSynWeight() {
        return maxSynWeight;
    }

    /**
     * Sets the value of the maxSynWeight property.
     * 
     */
    public void setMaxSynWeight(double value) {
        this.maxSynWeight = value;
    }

    /**
     * Gets the value of the postSpikeThresh property.
     * 
     */
    public double getPostSpikeThresh() {
        return postSpikeThresh;
    }

    /**
     * Sets the value of the postSpikeThresh property.
     * 
     */
    public void setPostSpikeThresh(double value) {
        this.postSpikeThresh = value;
    }

}
