//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.channelml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A synaptic mechanism implementing basic Spike Timing Dependent Plasticity based on Song and Abbott, 2001
 * 
 * Extends MultiDecaySynapse
 * 
 * <p>Java class for StdpSynapse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StdpSynapse">
 *   &lt;complexContent>
 *     &lt;extension base="{http://morphml.org/channelml/schema}MultiDecaySynapse">
 *       &lt;sequence>
 *         &lt;element name="spike_time_dep" type="{http://morphml.org/channelml/schema}StdpDep"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StdpSynapse", propOrder = {
    "spikeTimeDep"
})
public class StdpSynapse
    extends MultiDecaySynapse
{

    @XmlElement(name = "spike_time_dep", required = true)
    protected StdpDep spikeTimeDep;

    /**
     * Gets the value of the spikeTimeDep property.
     * 
     * @return
     *     possible object is
     *     {@link StdpDep }
     *     
     */
    public StdpDep getSpikeTimeDep() {
        return spikeTimeDep;
    }

    /**
     * Sets the value of the spikeTimeDep property.
     * 
     * @param value
     *     allowed object is
     *     {@link StdpDep }
     *     
     */
    public void setSpikeTimeDep(StdpDep value) {
        this.spikeTimeDep = value;
    }

}
