/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class unr_neurotranslate_util_NCSParser */

#ifndef _Included_unr_neurotranslate_util_NCSParser
#define _Included_unr_neurotranslate_util_NCSParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     unr_neurotranslate_util_NCSParser
 * Method:    ParseInput
 * Signature: (I[CI)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_unr_neurotranslate_util_NCSParser_ParseInput
  (JNIEnv *, jobject, jint, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
