//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.morphml.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.morphml.metadata.schema.Annotation;
import org.morphml.metadata.schema.GroupDetail;
import org.morphml.metadata.schema.LengthUnits;
import org.morphml.metadata.schema.Properties;
import org.morphml.metadata.schema.PropertyDetail;
import org.morphml.metadata.schema.VolumeUnits;


/**
 * The main element which details the neuronal morphology. Cells, various histological features, and
 *             properties associated with the data can be contained in this element
 * 
 * <p>Java class for Morphology complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Morphology">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://morphml.org/metadata/schema}metadata"/>
 *         &lt;element name="cells" type="{http://morphml.org/morphml/schema}Cells"/>
 *         &lt;element name="features" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{http://morphml.org/metadata/schema}metadata"/>
 *                   &lt;element name="feature" type="{http://morphml.org/morphml/schema}Feature" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="propertyDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="propertyDetail" type="{http://morphml.org/metadata/schema}PropertyDetail" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="groupDetails" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="groupDetail" type="{http://morphml.org/metadata/schema}GroupDetail" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lengthUnits" type="{http://morphml.org/metadata/schema}LengthUnits" />
 *       &lt;attribute name="length_units" type="{http://morphml.org/metadata/schema}LengthUnits" />
 *       &lt;attribute name="volumeUnits" type="{http://morphml.org/metadata/schema}VolumeUnits" default="cubic_millimeter" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Morphology", propOrder = {
    "notes",
    "properties",
    "annotation",
    "groups",
    "cells",
    "features",
    "propertyDetails",
    "groupDetails"
})
@XmlRootElement(name = "morphml")
public class Morphml {

    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected String notes;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Properties properties;
    @XmlElement(namespace = "http://morphml.org/metadata/schema")
    protected Annotation annotation;
    @XmlElement(name = "group", namespace = "http://morphml.org/metadata/schema")
    protected List<String> groups;
    @XmlElement(required = true)
    protected Cells cells;
    protected Morphml.Features features;
    protected Morphml.PropertyDetails propertyDetails;
    protected Morphml.GroupDetails groupDetails;
    @XmlAttribute
    protected String name;
    @XmlAttribute(name = "lengthUnits")
    protected LengthUnits morphMLLengthUnits;
    @XmlAttribute(name = "length_units")
    protected LengthUnits lengthUnits;
    @XmlAttribute
    protected VolumeUnits volumeUnits;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the properties property.
     * 
     * @return
     *     possible object is
     *     {@link Properties }
     *     
     */
    public Properties getProperties() {
        return properties;
    }

    /**
     * Sets the value of the properties property.
     * 
     * @param value
     *     allowed object is
     *     {@link Properties }
     *     
     */
    public void setProperties(Properties value) {
        this.properties = value;
    }

    /**
     * Gets the value of the annotation property.
     * 
     * @return
     *     possible object is
     *     {@link Annotation }
     *     
     */
    public Annotation getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotation }
     *     
     */
    public void setAnnotation(Annotation value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGroups() {
        if (groups == null) {
            groups = new ArrayList<String>();
        }
        return this.groups;
    }

    /**
     * Gets the value of the cells property.
     * 
     * @return
     *     possible object is
     *     {@link Cells }
     *     
     */
    public Cells getCells() {
        return cells;
    }

    /**
     * Sets the value of the cells property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cells }
     *     
     */
    public void setCells(Cells value) {
        this.cells = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Morphml.Features }
     *     
     */
    public Morphml.Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Morphml.Features }
     *     
     */
    public void setFeatures(Morphml.Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the propertyDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Morphml.PropertyDetails }
     *     
     */
    public Morphml.PropertyDetails getPropertyDetails() {
        return propertyDetails;
    }

    /**
     * Sets the value of the propertyDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Morphml.PropertyDetails }
     *     
     */
    public void setPropertyDetails(Morphml.PropertyDetails value) {
        this.propertyDetails = value;
    }

    /**
     * Gets the value of the groupDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Morphml.GroupDetails }
     *     
     */
    public Morphml.GroupDetails getGroupDetails() {
        return groupDetails;
    }

    /**
     * Sets the value of the groupDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Morphml.GroupDetails }
     *     
     */
    public void setGroupDetails(Morphml.GroupDetails value) {
        this.groupDetails = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the morphMLLengthUnits property.
     * 
     * @return
     *     possible object is
     *     {@link LengthUnits }
     *     
     */
    public LengthUnits getMorphMLLengthUnits() {
        return morphMLLengthUnits;
    }

    /**
     * Sets the value of the morphMLLengthUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthUnits }
     *     
     */
    public void setMorphMLLengthUnits(LengthUnits value) {
        this.morphMLLengthUnits = value;
    }

    /**
     * Gets the value of the lengthUnits property.
     * 
     * @return
     *     possible object is
     *     {@link LengthUnits }
     *     
     */
    public LengthUnits getLengthUnits() {
        return lengthUnits;
    }

    /**
     * Sets the value of the lengthUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthUnits }
     *     
     */
    public void setLengthUnits(LengthUnits value) {
        this.lengthUnits = value;
    }

    /**
     * Gets the value of the volumeUnits property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeUnits }
     *     
     */
    public VolumeUnits getVolumeUnits() {
        if (volumeUnits == null) {
            return VolumeUnits.CUBIC_MILLIMETER;
        } else {
            return volumeUnits;
        }
    }

    /**
     * Sets the value of the volumeUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeUnits }
     *     
     */
    public void setVolumeUnits(VolumeUnits value) {
        this.volumeUnits = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{http://morphml.org/metadata/schema}metadata"/>
     *         &lt;element name="feature" type="{http://morphml.org/morphml/schema}Feature" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notes",
        "properties",
        "annotation",
        "groups",
        "features"
    })
    public static class Features {

        @XmlElement(namespace = "http://morphml.org/metadata/schema")
        protected String notes;
        @XmlElement(namespace = "http://morphml.org/metadata/schema")
        protected Properties properties;
        @XmlElement(namespace = "http://morphml.org/metadata/schema")
        protected Annotation annotation;
        @XmlElement(name = "group", namespace = "http://morphml.org/metadata/schema")
        protected List<String> groups;
        @XmlElement(name = "feature", required = true)
        protected List<Feature> features;

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

        /**
         * Gets the value of the properties property.
         * 
         * @return
         *     possible object is
         *     {@link Properties }
         *     
         */
        public Properties getProperties() {
            return properties;
        }

        /**
         * Sets the value of the properties property.
         * 
         * @param value
         *     allowed object is
         *     {@link Properties }
         *     
         */
        public void setProperties(Properties value) {
            this.properties = value;
        }

        /**
         * Gets the value of the annotation property.
         * 
         * @return
         *     possible object is
         *     {@link Annotation }
         *     
         */
        public Annotation getAnnotation() {
            return annotation;
        }

        /**
         * Sets the value of the annotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Annotation }
         *     
         */
        public void setAnnotation(Annotation value) {
            this.annotation = value;
        }

        /**
         * Gets the value of the groups property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groups property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroups().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getGroups() {
            if (groups == null) {
                groups = new ArrayList<String>();
            }
            return this.groups;
        }

        /**
         * Gets the value of the features property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the features property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFeatures().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Feature }
         * 
         * 
         */
        public List<Feature> getFeatures() {
            if (features == null) {
                features = new ArrayList<Feature>();
            }
            return this.features;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="groupDetail" type="{http://morphml.org/metadata/schema}GroupDetail" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "groupDetails"
    })
    public static class GroupDetails {

        @XmlElement(name = "groupDetail", required = true)
        protected List<GroupDetail> groupDetails;

        /**
         * Gets the value of the groupDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the groupDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGroupDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GroupDetail }
         * 
         * 
         */
        public List<GroupDetail> getGroupDetails() {
            if (groupDetails == null) {
                groupDetails = new ArrayList<GroupDetail>();
            }
            return this.groupDetails;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="propertyDetail" type="{http://morphml.org/metadata/schema}PropertyDetail" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "propertyDetails"
    })
    public static class PropertyDetails {

        @XmlElement(name = "propertyDetail", required = true)
        protected List<PropertyDetail> propertyDetails;

        /**
         * Gets the value of the propertyDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the propertyDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPropertyDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PropertyDetail }
         * 
         * 
         */
        public List<PropertyDetail> getPropertyDetails() {
            if (propertyDetails == null) {
                propertyDetails = new ArrayList<PropertyDetail>();
            }
            return this.propertyDetails;
        }

    }

}
