//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.morphml.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.morphml.morphml.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.morphml.morphml.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cell.Spines }
     * 
     */
    public Cell.Spines createCellSpines() {
        return new Cell.Spines();
    }

    /**
     * Create an instance of {@link Cell.Segments }
     * 
     */
    public Cell.Segments createCellSegments() {
        return new Cell.Segments();
    }

    /**
     * Create an instance of {@link InhomogeneousParam }
     * 
     */
    public InhomogeneousParam createInhomogeneousParam() {
        return new InhomogeneousParam();
    }

    /**
     * Create an instance of {@link FreePoints }
     * 
     */
    public FreePoints createFreePoints() {
        return new FreePoints();
    }

    /**
     * Create an instance of {@link Cell.CellBody }
     * 
     */
    public Cell.CellBody createCellCellBody() {
        return new Cell.CellBody();
    }

    /**
     * Create an instance of {@link Cell.Cables }
     * 
     */
    public Cell.Cables createCellCables() {
        return new Cell.Cables();
    }

    /**
     * Create an instance of {@link Spine }
     * 
     */
    public Spine createSpine() {
        return new Spine();
    }

    /**
     * Create an instance of {@link Morphml.GroupDetails }
     * 
     */
    public Morphml.GroupDetails createMorphmlGroupDetails() {
        return new Morphml.GroupDetails();
    }

    /**
     * Create an instance of {@link Morphml.Features }
     * 
     */
    public Morphml.Features createMorphmlFeatures() {
        return new Morphml.Features();
    }

    /**
     * Create an instance of {@link Morphml }
     * 
     */
    public Morphml createMorphml() {
        return new Morphml();
    }

    /**
     * Create an instance of {@link CableGroup.Cable }
     * 
     */
    public CableGroup.Cable createCableGroupCable() {
        return new CableGroup.Cable();
    }

    /**
     * Create an instance of {@link Cell }
     * 
     */
    public Cell createCell() {
        return new Cell();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link Cells }
     * 
     */
    public Cells createCells() {
        return new Cells();
    }

    /**
     * Create an instance of {@link Segment }
     * 
     */
    public Segment createSegment() {
        return new Segment();
    }

    /**
     * Create an instance of {@link Morphml.PropertyDetails }
     * 
     */
    public Morphml.PropertyDetails createMorphmlPropertyDetails() {
        return new Morphml.PropertyDetails();
    }

    /**
     * Create an instance of {@link CableGroup }
     * 
     */
    public CableGroup createCableGroup() {
        return new CableGroup();
    }

    /**
     * Create an instance of {@link InhomogeneousParam.Distal }
     * 
     */
    public InhomogeneousParam.Distal createInhomogeneousParamDistal() {
        return new InhomogeneousParam.Distal();
    }

    /**
     * Create an instance of {@link org.morphml.morphml.schema.Cable }
     * 
     */
    public org.morphml.morphml.schema.Cable createCable() {
        return new org.morphml.morphml.schema.Cable();
    }

    /**
     * Create an instance of {@link InhomogeneousParam.Proximal }
     * 
     */
    public InhomogeneousParam.Proximal createInhomogeneousParamProximal() {
        return new InhomogeneousParam.Proximal();
    }

    /**
     * Create an instance of {@link Path }
     * 
     */
    public Path createPath() {
        return new Path();
    }

}
