//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.biophysics.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This quantity is often required for computational simulations and specifies the potential
 *                 difference across the membrane at the start of the simulation. This is an optional field
 * 
 * <p>Java class for InitialMembPotential complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitialMembPotential">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parameter" type="{http://morphml.org/biophysics/schema}UnnamedParameter" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variableParameter" type="{http://morphml.org/biophysics/schema}VariableParameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitialMembPotential", propOrder = {
    "parameters",
    "variableParameters"
})
public class InitialMembPotential {

    @XmlElement(name = "parameter")
    protected List<UnnamedParameter> parameters;
    @XmlElement(name = "variableParameter")
    protected List<VariableParameter> variableParameters;

    /**
     * Gets the value of the parameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UnnamedParameter }
     * 
     * 
     */
    public List<UnnamedParameter> getParameters() {
        if (parameters == null) {
            parameters = new ArrayList<UnnamedParameter>();
        }
        return this.parameters;
    }

    /**
     * Gets the value of the variableParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variableParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariableParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariableParameter }
     * 
     * 
     */
    public List<VariableParameter> getVariableParameters() {
        if (variableParameters == null) {
            variableParameters = new ArrayList<VariableParameter>();
        }
        return this.variableParameters;
    }

}
