//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.biophysics.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MechanismType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MechanismType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Channel Mechanism"/>
 *     &lt;enumeration value="Ion Concentration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MechanismType")
@XmlEnum
public enum MechanismType {


    /**
     * Voltage and/or conductance dependent membrane conductance
     * 
     */
    @XmlEnumValue("Channel Mechanism")
    CHANNEL_MECHANISM("Channel Mechanism"),

    /**
     * Mechanism which alters the oncentration of a specific ion
     * 
     */
    @XmlEnumValue("Ion Concentration")
    ION_CONCENTRATION("Ion Concentration");
    private final String value;

    MechanismType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MechanismType fromValue(String v) {
        for (MechanismType c: MechanismType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
