//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.biophysics.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.morphml.biophysics.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Biophysics_QNAME = new QName("http://morphml.org/biophysics/schema", "biophysics");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.morphml.biophysics.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NamedParameter }
     * 
     */
    public NamedParameter createNamedParameter() {
        return new NamedParameter();
    }

    /**
     * Create an instance of {@link VariableNamedParameter }
     * 
     */
    public VariableNamedParameter createVariableNamedParameter() {
        return new VariableNamedParameter();
    }

    /**
     * Create an instance of {@link Mechanism }
     * 
     */
    public Mechanism createMechanism() {
        return new Mechanism();
    }

    /**
     * Create an instance of {@link SpecAxialResistance }
     * 
     */
    public SpecAxialResistance createSpecAxialResistance() {
        return new SpecAxialResistance();
    }

    /**
     * Create an instance of {@link BiophysicsType }
     * 
     */
    public BiophysicsType createBiophysicsType() {
        return new BiophysicsType();
    }

    /**
     * Create an instance of {@link InhomogeneousValue }
     * 
     */
    public InhomogeneousValue createInhomogeneousValue() {
        return new InhomogeneousValue();
    }

    /**
     * Create an instance of {@link VariableParameter }
     * 
     */
    public VariableParameter createVariableParameter() {
        return new VariableParameter();
    }

    /**
     * Create an instance of {@link InitialMembPotential }
     * 
     */
    public InitialMembPotential createInitialMembPotential() {
        return new InitialMembPotential();
    }

    /**
     * Create an instance of {@link IonProperties }
     * 
     */
    public IonProperties createIonProperties() {
        return new IonProperties();
    }

    /**
     * Create an instance of {@link SpecCapacitance }
     * 
     */
    public SpecCapacitance createSpecCapacitance() {
        return new SpecCapacitance();
    }

    /**
     * Create an instance of {@link UnnamedParameter }
     * 
     */
    public UnnamedParameter createUnnamedParameter() {
        return new UnnamedParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BiophysicsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://morphml.org/biophysics/schema", name = "biophysics")
    public JAXBElement<BiophysicsType> createBiophysics(BiophysicsType value) {
        return new JAXBElement<BiophysicsType>(_Biophysics_QNAME, BiophysicsType.class, null, value);
    }

}
