//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.networkml.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information on synapse type and default values for weight, delay, threshold, etc.
 * 
 * <p>Java class for GlobalSynapticProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GlobalSynapticProperties">
 *   &lt;complexContent>
 *     &lt;extension base="{http://morphml.org/networkml/schema}SynapseInternalProperties">
 *       &lt;sequence>
 *         &lt;element name="synapse_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="default_values" type="{http://morphml.org/networkml/schema}SynapseInternalProperties" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="synapse_type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GlobalSynapticProperties", propOrder = {
    "globalSynapseType",
    "defaultValues"
})
public class GlobalSynapticProperties
    extends SynapseInternalProperties
{

    @XmlElement(name = "synapse_type")
    protected String globalSynapseType;
    @XmlElement(name = "default_values")
    protected SynapseInternalProperties defaultValues;
    @XmlAttribute(name = "synapse_type")
    protected String synapseType;

    /**
     * Gets the value of the globalSynapseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalSynapseType() {
        return globalSynapseType;
    }

    /**
     * Sets the value of the globalSynapseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalSynapseType(String value) {
        this.globalSynapseType = value;
    }

    /**
     * Gets the value of the defaultValues property.
     * 
     * @return
     *     possible object is
     *     {@link SynapseInternalProperties }
     *     
     */
    public SynapseInternalProperties getDefaultValues() {
        return defaultValues;
    }

    /**
     * Sets the value of the defaultValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link SynapseInternalProperties }
     *     
     */
    public void setDefaultValues(SynapseInternalProperties value) {
        this.defaultValues = value;
    }

    /**
     * Gets the value of the synapseType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynapseType() {
        return synapseType;
    }

    /**
     * Sets the value of the synapseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynapseType(String value) {
        this.synapseType = value;
    }

}
