//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.metadata.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A reference to an author 
 *                             Note: This element will possibly change when a new set of schema 
 *                             files is adopted for adding references, authors, citations, etc. See 
 *                 mailing lists for latest status
 * 
 * <p>Java class for Authors complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Authors">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modelAuthor" type="{http://morphml.org/metadata/schema}Person" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="modelTranslator" type="{http://morphml.org/metadata/schema}Person" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Authors", propOrder = {
    "modelAuthors",
    "modelTranslators"
})
public class Authors {

    @XmlElement(name = "modelAuthor")
    protected List<Person> modelAuthors;
    @XmlElement(name = "modelTranslator")
    protected List<Person> modelTranslators;

    /**
     * Gets the value of the modelAuthors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelAuthors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelAuthors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Person }
     * 
     * 
     */
    public List<Person> getModelAuthors() {
        if (modelAuthors == null) {
            modelAuthors = new ArrayList<Person>();
        }
        return this.modelAuthors;
    }

    /**
     * Gets the value of the modelTranslators property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelTranslators property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelTranslators().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Person }
     * 
     * 
     */
    public List<Person> getModelTranslators() {
        if (modelTranslators == null) {
            modelTranslators = new ArrayList<Person>();
        }
        return this.modelTranslators;
    }

}
