//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.13 at 04:28:34 PM PDT 
//


package org.morphml.metadata.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatusValue.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StatusValue">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stable"/>
 *     &lt;enumeration value="in_progress"/>
 *     &lt;enumeration value="known_issues"/>
 *     &lt;enumeration value="deprecated"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StatusValue")
@XmlEnum
public enum StatusValue {


    /**
     * File can be used with reasonable confidence
     * 
     */
    @XmlEnumValue("stable")
    STABLE("stable"),

    /**
     * File can be used with caution, bearing in mind any comments present
     * 
     */
    @XmlEnumValue("in_progress")
    IN_PROGRESS("in_progress"),

    /**
     * File can be assumed to be erroneous and shouldn't be used
     * 
     */
    @XmlEnumValue("known_issues")
    KNOWN_ISSUES("known_issues"),

    /**
     * File uses constructs which have been superceded in current version of specification
     * 
     */
    @XmlEnumValue("deprecated")
    DEPRECATED("deprecated");
    private final String value;

    StatusValue(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusValue fromValue(String v) {
        for (StatusValue c: StatusValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
